version: '3'

services:
  db:
    container_name: 'migrations_postgres'
    image: 'postgres:17'
    restart: always
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'